-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS locadoraDB;
USE locadoraDB;

-- Tabela de Clientes
CREATE TABLE TB_CLIENTE (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NM_CLIENTE VARCHAR(200) NOT NULL,
    DS_CPF VARCHAR(50) NOT NULL,
    DS_TELEFONE VARCHAR(50) NOT NULL,
    DS_EMAIL VARCHAR(100) NOT NULL,
    DS_CNH VARCHAR(50) NOT NULL
);

-- Tabela de Tipos de Veículos
CREATE TABLE TB_TIPO_VEICULO (
    ID_TIPO_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
    DS_TIPO VARCHAR(100) NOT NULL
);

-- Tabela de Veículos
CREATE TABLE TB_VEICULO (
    ID_VEICULO INT PRIMARY KEY AUTO_INCREMENT,
    ID_TIPO_VEICULO INT NOT NULL,
    DS_MODELO VARCHAR(50) NOT NULL,
    DS_MARCA VARCHAR(50) NOT NULL,
    DS_PLACA VARCHAR(50) NOT NULL,
    NR_ANO INT NOT NULL,
    FOREIGN KEY (ID_TIPO_VEICULO) REFERENCES TB_TIPO_VEICULO(ID_TIPO_VEICULO)
);

-- Tabela de Locações
CREATE TABLE TB_LOCACAO (
    ID_LOCACAO INT PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_VEICULO INT NOT NULL,
    DT_LOCACAO DATETIME NOT NULL,
    NR_KM_RETIRADA INT NOT NULL,
    BT_SEGURO BOOL NOT NULL,
    DS_OBSERVACAO VARCHAR(500) NULL,
    DS_SITUACAO VARCHAR(50) NOT NULL DEFAULT 'pendente',
    NR_KM_ENTREGA INT NULL,
    DT_ENTREGA DATETIME NULL,
    VL_TOTAL DECIMAL(15,2) NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_VEICULO) REFERENCES TB_VEICULO(ID_VEICULO)
);

-- Inserção de dados de exemplo
INSERT INTO TB_TIPO_VEICULO (DS_TIPO) VALUES 
    ('Hatch'),
    ('SUV'),
    ('Utilitário'),
    ('Sedan'),
    ('Pickup');

-- Dados de exemplo para testes
INSERT INTO TB_CLIENTE (NM_CLIENTE, DS_CPF, DS_TELEFONE, DS_EMAIL, DS_CNH) VALUES 
    ('João Silva', '123.456.789-00', '(11) 99999-8888', 'joao@email.com', '12345678901'),
    ('Maria Santos', '987.654.321-00', '(11) 88888-7777', 'maria@email.com', '10987654321');

INSERT INTO TB_VEICULO (ID_TIPO_VEICULO, DS_MODELO, DS_MARCA, NR_ANO, DS_PLACA) VALUES
    (1, 'Civic', 'Honda', 2020, 'ABC-1234'),
    (2, 'HR-V', 'Honda', 2021, 'DEF-5678'),
    (1, 'Corolla', 'Toyota', 2019, 'GHI-9012');

SELECT 'Banco de dados locadoraDB criado com sucesso!' AS resultado;